/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/04/15': RouteRecordInfo<
      '/posts/2025/04/15',
      '/posts/2025/04/15',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/04/16': RouteRecordInfo<
      '/posts/2025/04/16',
      '/posts/2025/04/16',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/04/17': RouteRecordInfo<
      '/posts/2025/04/17',
      '/posts/2025/04/17',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/04/18': RouteRecordInfo<
      '/posts/2025/04/18',
      '/posts/2025/04/18',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/04/19': RouteRecordInfo<
      '/posts/2025/04/19',
      '/posts/2025/04/19',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/05/10': RouteRecordInfo<
      '/posts/2025/05/10',
      '/posts/2025/05/10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/07/11': RouteRecordInfo<
      '/posts/2025/07/11',
      '/posts/2025/07/11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/07/26': RouteRecordInfo<
      '/posts/2025/07/26',
      '/posts/2025/07/26',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/07/30': RouteRecordInfo<
      '/posts/2025/07/30',
      '/posts/2025/07/30',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/08/12': RouteRecordInfo<
      '/posts/2025/08/12',
      '/posts/2025/08/12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025/12/06': RouteRecordInfo<
      '/posts/2025/12/06',
      '/posts/2025/12/06',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/0': RouteRecordInfo<
      '/posts/loser-economics/0',
      '/posts/loser-economics/0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/1': RouteRecordInfo<
      '/posts/loser-economics/1',
      '/posts/loser-economics/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/2': RouteRecordInfo<
      '/posts/loser-economics/2',
      '/posts/loser-economics/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/3': RouteRecordInfo<
      '/posts/loser-economics/3',
      '/posts/loser-economics/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/4': RouteRecordInfo<
      '/posts/loser-economics/4',
      '/posts/loser-economics/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/5': RouteRecordInfo<
      '/posts/loser-economics/5',
      '/posts/loser-economics/5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/6': RouteRecordInfo<
      '/posts/loser-economics/6',
      '/posts/loser-economics/6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/7': RouteRecordInfo<
      '/posts/loser-economics/7',
      '/posts/loser-economics/7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/loser-economics/appendix': RouteRecordInfo<
      '/posts/loser-economics/appendix',
      '/posts/loser-economics/appendix',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.10_@babel+parse_f7f0dd037ffc81e0aa6bdfb9cac09860/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/2025/04/15.md': {
      routes:
        | '/posts/2025/04/15'
      views:
        | never
    }
    'pages/posts/2025/04/16.md': {
      routes:
        | '/posts/2025/04/16'
      views:
        | never
    }
    'pages/posts/2025/04/17.md': {
      routes:
        | '/posts/2025/04/17'
      views:
        | never
    }
    'pages/posts/2025/04/18.md': {
      routes:
        | '/posts/2025/04/18'
      views:
        | never
    }
    'pages/posts/2025/04/19.md': {
      routes:
        | '/posts/2025/04/19'
      views:
        | never
    }
    'pages/posts/2025/05/10.md': {
      routes:
        | '/posts/2025/05/10'
      views:
        | never
    }
    'pages/posts/2025/07/11.md': {
      routes:
        | '/posts/2025/07/11'
      views:
        | never
    }
    'pages/posts/2025/07/26.md': {
      routes:
        | '/posts/2025/07/26'
      views:
        | never
    }
    'pages/posts/2025/07/30.md': {
      routes:
        | '/posts/2025/07/30'
      views:
        | never
    }
    'pages/posts/2025/08/12.md': {
      routes:
        | '/posts/2025/08/12'
      views:
        | never
    }
    'pages/posts/2025/12/06.md': {
      routes:
        | '/posts/2025/12/06'
      views:
        | never
    }
    'pages/posts/loser-economics/0.md': {
      routes:
        | '/posts/loser-economics/0'
      views:
        | never
    }
    'pages/posts/loser-economics/1.md': {
      routes:
        | '/posts/loser-economics/1'
      views:
        | never
    }
    'pages/posts/loser-economics/2.md': {
      routes:
        | '/posts/loser-economics/2'
      views:
        | never
    }
    'pages/posts/loser-economics/3.md': {
      routes:
        | '/posts/loser-economics/3'
      views:
        | never
    }
    'pages/posts/loser-economics/4.md': {
      routes:
        | '/posts/loser-economics/4'
      views:
        | never
    }
    'pages/posts/loser-economics/5.md': {
      routes:
        | '/posts/loser-economics/5'
      views:
        | never
    }
    'pages/posts/loser-economics/6.md': {
      routes:
        | '/posts/loser-economics/6'
      views:
        | never
    }
    'pages/posts/loser-economics/7.md': {
      routes:
        | '/posts/loser-economics/7'
      views:
        | never
    }
    'pages/posts/loser-economics/appendix.md': {
      routes:
        | '/posts/loser-economics/appendix'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
