/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2025-04-15': RouteRecordInfo<'/posts/2025-04-15', '/posts/2025-04-15', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/0': RouteRecordInfo<'/posts/loser-economics/0', '/posts/loser-economics/0', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/1': RouteRecordInfo<'/posts/loser-economics/1', '/posts/loser-economics/1', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/2': RouteRecordInfo<'/posts/loser-economics/2', '/posts/loser-economics/2', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/3': RouteRecordInfo<'/posts/loser-economics/3', '/posts/loser-economics/3', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/4': RouteRecordInfo<'/posts/loser-economics/4', '/posts/loser-economics/4', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/5': RouteRecordInfo<'/posts/loser-economics/5', '/posts/loser-economics/5', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/6': RouteRecordInfo<'/posts/loser-economics/6', '/posts/loser-economics/6', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/7': RouteRecordInfo<'/posts/loser-economics/7', '/posts/loser-economics/7', Record<never, never>, Record<never, never>>,
    '/posts/loser-economics/appendix': RouteRecordInfo<'/posts/loser-economics/appendix', '/posts/loser-economics/appendix', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
